# Generated by Django 5.2.8 on 2026-01-04 23:18

import django.core.validators
import django.db.models.deletion
import service_desk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Redirects non-admins to a maintenance page",
                    ),
                ),
                (
                    "use_mock_data",
                    models.BooleanField(
                        default=False,
                        help_text="Toggle between live data and demo data",
                    ),
                ),
                (
                    "kb_recommendation_logic",
                    models.CharField(
                        choices=[
                            ("views", "Most Viewed"),
                            ("updated", "Recently Updated"),
                            ("random", "Random Selection"),
                        ],
                        default="updated",
                        help_text="How to sort KB articles on homepage",
                        max_length=20,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        default="859-977-9641",
                        help_text="Primary support phone number",
                        max_length=20,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@primeeng.com",
                        help_text="Primary support email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        default="Mon-Fri, 8:00 AM - 5:00 PM EST",
                        help_text="Support availability hours",
                        max_length=100,
                    ),
                ),
                (
                    "announcement_title",
                    models.CharField(
                        default="All Systems Operational",
                        help_text="Title of the system health announcement",
                        max_length=200,
                    ),
                ),
                (
                    "announcement_message",
                    models.TextField(
                        default="No known issues at this time.",
                        help_text="Message content for the system health announcement",
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        default="info",
                        help_text="Type of the announcement (e.g., info, warning, alert, critical)",
                        max_length=50,
                    ),
                ),
                (
                    "announcement_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time for the announcement (optional)",
                        null=True,
                    ),
                ),
                (
                    "announcement_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End time for the announcement (optional)",
                        null=True,
                    ),
                ),
                (
                    "vendor_status",
                    models.JSONField(
                        default=list,
                        help_text="List of vendor statuses (stored as JSON)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "auto_route_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Ticket Types that route here by default",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("Application Problem", "Application Problem"),
                            ("Email/Mailbox Help", "Email/Mailbox Help"),
                            ("Hardware Issue", "Hardware Issue"),
                            ("IT Service Request", "IT Service Request"),
                            ("Printer / Scanner Issue", "Printer / Scanner Issue"),
                            ("Software Installation", "Software Installation"),
                            ("General Question", "General Question"),
                            ("VP Password Reset", "VP Password Reset"),
                            ("VP Permissions", "VP Permissions"),
                        ],
                        default="IT Service Request",
                        max_length=50,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Error / Not Working", "Error / Not Working"),
                            ("General Inquiry", "General Inquiry"),
                            ("Install / Setup", "Install / Setup"),
                            ("Permissions", "Permissions"),
                            ("Request / Change", "Request / Change"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Awaiting 3rd Party", "Awaiting 3rd Party"),
                            ("Awaiting Part", "Awaiting Part"),
                            ("Investigating", "Investigating"),
                            ("Monitoring", "Monitoring"),
                            ("Working", "Working"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Portal", "Portal"),
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                        ],
                        default="Portal",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Priority 1 - Critical", "Priority 1 - Critical"),
                            ("Priority 2 - High", "Priority 2 - High"),
                            ("Priority 3 - Medium", "Priority 3 - Medium"),
                            ("Priority 4 - Low", "Priority 4 - Low"),
                            ("Standard", "Standard"),
                        ],
                        default="Priority 3 - Medium",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("User Commented", "User Commented"),
                            ("Work In Progress", "Work In Progress"),
                            ("Reopened", "Reopened"),
                            ("Assigned", "Assigned"),
                            ("In Progress", "In Progress"),
                            ("Awaiting User Reply", "Awaiting User Reply"),
                            ("On Hold", "On Hold"),
                            ("Resolved", "Resolved"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="New",
                        max_length=30,
                    ),
                ),
                (
                    "application_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the affected application",
                        max_length=100,
                    ),
                ),
                (
                    "computer_name",
                    models.CharField(
                        blank=True,
                        help_text="Computer name or asset tag",
                        max_length=100,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="Type of hardware device", max_length=100
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        help_text="Asset tag or serial number",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location of device",
                        max_length=100,
                    ),
                ),
                (
                    "printer_location",
                    models.CharField(
                        blank=True, help_text="Printer/Scanner location", max_length=100
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Affected email address or mailbox",
                        max_length=254,
                    ),
                ),
                (
                    "mailbox_name",
                    models.CharField(
                        blank=True,
                        help_text="Shared mailbox or distribution list name",
                        max_length=100,
                    ),
                ),
                (
                    "software_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of software to install",
                        max_length=100,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Business justification for software"
                    ),
                ),
                (
                    "license_info",
                    models.TextField(
                        blank=True, help_text="License information if known"
                    ),
                ),
                (
                    "deltek_username",
                    models.CharField(
                        blank=True, help_text="Deltek/VP username", max_length=100
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        help_text="Affected project name/number",
                        max_length=100,
                    ),
                ),
                (
                    "requested_access",
                    models.CharField(
                        blank=True, help_text="Type of access requested", max_length=200
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        help_text="Manager name for approval",
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Screenshot or supporting document (max 5 MB)",
                        null=True,
                        upload_to="ticket_attachments/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "txt",
                                    "log",
                                ]
                            ),
                            service_desk.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "connectwise_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the first interaction/assignment by a technician.",
                        null=True,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the ticket was resolved/closed.",
                        null=True,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="service_desk.serviceboard",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Ticket",
                "verbose_name_plural": "Service Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSATSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 (Poor) to 5 (Excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback comment"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="service_desk.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSAT Survey",
                "verbose_name_plural": "CSAT Surveys",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_internal", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="service_desk.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connectwise_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="Employee", max_length=100),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        default="PRIME AE Group, Inc.",
                        help_text="Company Name",
                        max_length=100,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        default="Marty McFly",
                        help_text="Direct Supervisor",
                        max_length=100,
                    ),
                ),
                (
                    "prefer_initials",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, displays initials instead of the profile picture.",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Architecture", "Architecture"),
                            ("Corporate", "Corporate"),
                            ("Land", "Land"),
                            ("Transportation", "Transportation"),
                        ],
                        default="Corporate",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Akron, OH (W Market St)", "Akron, OH (W Market St)"),
                            (
                                "Albany, NY (Great Oaks Blvd)",
                                "Albany, NY (Great Oaks Blvd)",
                            ),
                            (
                                "Baltimore, MD (Research Park Dr)",
                                "Baltimore, MD (Research Park Dr)",
                            ),
                            ("Bluffton, SC (Main St)", "Bluffton, SC (Main St)"),
                            (
                                "Cincinnati, OH (Kenwood Rd)",
                                "Cincinnati, OH (Kenwood Rd)",
                            ),
                            (
                                "Clarksville, IN (Quartermaster Ct)",
                                "Clarksville, IN (Quartermaster Ct)",
                            ),
                            ("Columbus, OH (Lyra Dr)", "Columbus, OH (Lyra Dr)"),
                            (
                                "Fairfax, VA (Fair Ridge Dr)",
                                "Fairfax, VA (Fair Ridge Dr)",
                            ),
                            (
                                "Fort Myers, FL (International Center)",
                                "Fort Myers, FL (International Center)",
                            ),
                            (
                                "Harrisburg, PA (Highlands Plaza Dr)",
                                "Harrisburg, PA (Highlands Plaza Dr)",
                            ),
                            (
                                "Indianapolis, IN (W 96th St)",
                                "Indianapolis, IN (W 96th St)",
                            ),
                            (
                                "Jacksonville, FL (Belfort Pkwy)",
                                "Jacksonville, FL (Belfort Pkwy)",
                            ),
                            (
                                "Jacksonville, FL (Sutton Park Dr)",
                                "Jacksonville, FL (Sutton Park Dr)",
                            ),
                            (
                                "Lake Mary, FL (International Pkwy)",
                                "Lake Mary, FL (International Pkwy)",
                            ),
                            (
                                "Lexington, KY (Corporate Dr)",
                                "Lexington, KY (Corporate Dr)",
                            ),
                            ("Louisville, KY (N 7th St)", "Louisville, KY (N 7th St)"),
                            (
                                "Maitland, FL (Maitland Center Pkwy)",
                                "Maitland, FL (Maitland Center Pkwy)",
                            ),
                            ("Morehead, KY (E Main St)", "Morehead, KY (E Main St)"),
                            (
                                "New Albany, IN (Technology Ave)",
                                "New Albany, IN (Technology Ave)",
                            ),
                            ("Orlando, FL (E Pine St)", "Orlando, FL (E Pine St)"),
                            (
                                "Pensacola, FL (W Garden St)",
                                "Pensacola, FL (W Garden St)",
                            ),
                            (
                                "Richmond, VA (Arboretum Pkwy)",
                                "Richmond, VA (Arboretum Pkwy)",
                            ),
                            ("Tampa, FL (W Cypress St)", "Tampa, FL (W Cypress St)"),
                            (
                                "Weston, FL (N Commerce Pkwy)",
                                "Weston, FL (N Commerce Pkwy)",
                            ),
                            (
                                "Wethersfield, CT (Great Meadow Rd)",
                                "Wethersfield, CT (Great Meadow Rd)",
                            ),
                            ("Remote", "Remote"),
                        ],
                        default="Remote",
                        max_length=100,
                    ),
                ),
                ("phone_office", models.CharField(blank=True, max_length=20)),
                ("phone_mobile", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
