# Generated by Django 5.2.8 on 2025-11-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Summary of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed notes')),
                ('ticket_type', models.CharField(choices=[('Application', 'Application Issue'), ('Email', 'Email & Mailbox'), ('Hardware', 'Hardware Issue'), ('Printer', 'Printers & Scanners'), ('Software', 'Software Install'), ('General', 'General IT Question'), ('VP Password', 'Deltek VP Password Reset'), ('VP Permissions', 'VP Permissions Request'), ('Project', 'Project Folder Management')], default='General', max_length=50, verbose_name='Type')),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('Portal', 'Portal'), ('Email', 'Email'), ('Phone', 'Phone')], default='Portal', max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical - System Down'), ('High', 'High - Urgent'), ('Medium', 'Medium - Normal'), ('Low', 'Low - Scheduled'), ('NoResponse', 'Do Not Respond')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('connectwise_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Ticket',
                'verbose_name_plural': 'Service Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
