# Generated by Django 5.2.8 on 2026-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("service_desk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceboard",
            name="restricted_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="If selected, only users in these groups can view this board.",
                related_name="service_boards",
                to="auth.group",
            ),
        ),
    ]
