# Generated by Django 5.2.8 on 2025-12-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0002_alter_ticket_options_ticket_technician_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connectwise_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="Employee", max_length=100),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="General", max_length=100),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="Remote", max_length=100),
                ),
                ("phone_office", models.CharField(blank=True, max_length=20)),
                ("phone_mobile", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
