# Generated by Django 5.2.8 on 2026-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0002_serviceboard_restricted_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceboard",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="serviceboard",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in which to display the board"
            ),
        ),
    ]
