# Generated by Django 5.2.8 on 2026-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0003_alter_serviceboard_options_serviceboard_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Priority 1 - Critical", "Priority 1 - Critical"),
                    ("Priority 2 - High", "Priority 2 - High"),
                    ("Priority 3 - Medium", "Priority 3 - Medium"),
                    ("Priority 4 - Low", "Priority 4 - Low"),
                ],
                default="Priority 3 - Medium",
                max_length=30,
            ),
        ),
    ]
