# Generated by Django 5.2.8 on 2025-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Redirects non-admins to a maintenance page",
                    ),
                ),
                (
                    "use_mock_data",
                    models.BooleanField(
                        default=False,
                        help_text="Toggle between live data and demo data",
                    ),
                ),
                (
                    "kb_recommendation_logic",
                    models.CharField(
                        choices=[
                            ("views", "Most Viewed"),
                            ("updated", "Recently Updated"),
                            ("random", "Random Selection"),
                        ],
                        default="updated",
                        help_text="How to sort KB articles on homepage",
                        max_length=20,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        default="859-977-9641",
                        help_text="Primary support phone number",
                        max_length=20,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@primeeng.com",
                        help_text="Primary support email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        default="Mon-Fri, 8:00 AM - 5:00 PM EST",
                        help_text="Support availability hours",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
