# Generated by Django 5.2.8 on 2026-01-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0004_alter_ticket_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "form_class_name",
                    models.CharField(
                        default="GeneralQuestionForm",
                        help_text="Name of the Django Form class to load for this type.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_type",
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ticket",
            name="legacy_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="legacy_subtype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="legacy_ticket_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="source",
            field=models.CharField(
                choices=[
                    ("Portal", "Portal"),
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Walk-Up", "Walk-Up"),
                ],
                default="Portal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="service_desk.serviceitem",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="parent_subtypes",
            field=models.ManyToManyField(
                related_name="items", to="service_desk.servicesubtype"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="service_desk.servicesubtype",
            ),
        ),
        migrations.AddField(
            model_name="servicesubtype",
            name="parent_types",
            field=models.ManyToManyField(
                related_name="subtypes", to="service_desk.servicetype"
            ),
        ),
        migrations.AddField(
            model_name="serviceboard",
            name="allowed_types",
            field=models.ManyToManyField(
                blank=True, related_name="boards", to="service_desk.servicetype"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="service_desk.servicetype",
            ),
        ),
    ]
