# Generated by Django 5.2.8 on 2025-12-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0004_globalsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="use_mock_data",
            field=models.BooleanField(
                default=True, help_text="Toggle between live data and demo data"
            ),
        ),
    ]
