# Generated by Django 5.2.8 on 2026-01-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0005_serviceitem_servicesubtype_servicetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
