# Generated by Django 5.2.8 on 2025-12-21 02:03

import django.core.validators
import service_desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0005_alter_globalsettings_use_mock_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="application_name",
            field=models.CharField(
                blank=True, help_text="Name of the affected application", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="asset_tag",
            field=models.CharField(
                blank=True, help_text="Asset tag or serial number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Screenshot or supporting document (max 5 MB)",
                null=True,
                upload_to="ticket_attachments/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "txt",
                            "log",
                        ]
                    ),
                    service_desk.models.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="computer_name",
            field=models.CharField(
                blank=True, help_text="Computer name or asset tag", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="deltek_username",
            field=models.CharField(
                blank=True, help_text="Deltek/VP username", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="device_type",
            field=models.CharField(
                blank=True, help_text="Type of hardware device", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="email_address",
            field=models.EmailField(
                blank=True,
                help_text="Affected email address or mailbox",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="justification",
            field=models.TextField(
                blank=True, help_text="Business justification for software"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="license_info",
            field=models.TextField(
                blank=True, help_text="License information if known"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="location",
            field=models.CharField(
                blank=True, help_text="Physical location of device", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="mailbox_name",
            field=models.CharField(
                blank=True,
                help_text="Shared mailbox or distribution list name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="manager_name",
            field=models.CharField(
                blank=True, help_text="Manager name for approval", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="printer_location",
            field=models.CharField(
                blank=True, help_text="Printer/Scanner location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="project_name",
            field=models.CharField(
                blank=True, help_text="Affected project name/number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requested_access",
            field=models.CharField(
                blank=True, help_text="Type of access requested", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="software_name",
            field=models.CharField(
                blank=True, help_text="Name of software to install", max_length=100
            ),
        ),
    ]
