# Generated by Django 5.2.8 on 2025-12-21 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0006_ticket_application_name_ticket_asset_tag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Service Ticket",
                "verbose_name_plural": "Service Tickets",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="board",
            field=models.CharField(
                choices=[
                    ("Tier 1", "Tier 1"),
                    ("Tier 2", "Tier 2"),
                    ("Tier 3", "Tier 3"),
                ],
                default="Tier 1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="support_email",
            field=models.EmailField(
                default="primeit@primeeng.com",
                help_text="Primary support email address",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="item",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Awaiting 3rd Party", "Awaiting 3rd Party"),
                    ("Awaiting Part", "Awaiting Part"),
                    ("Investigating", "Investigating"),
                    ("Monitoring", "Monitoring"),
                    ("Working", "Working"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Priority 1 - Critical", "Priority 1 - Critical"),
                    ("Priority 2 - High", "Priority 2 - High"),
                    ("Priority 3 - Medium", "Priority 3 - Medium"),
                    ("Priority 4 - Low", "Priority 4 - Low"),
                    ("Standard", "Standard"),
                ],
                default="Priority 3 - Medium",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("User Commented", "User Commented"),
                    ("Work In Progress", "Work In Progress"),
                    ("Reopened", "Reopened"),
                    ("Assigned", "Assigned"),
                    ("In Progress", "In Progress"),
                    ("Awaiting User Reply", "Awaiting User Reply"),
                    ("On Hold", "On Hold"),
                    ("Resolved", "Resolved"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Error / Not Working", "Error / Not Working"),
                    ("General Inquiry", "General Inquiry"),
                    ("Install / Setup", "Install / Setup"),
                    ("Permissions", "Permissions"),
                    ("Request / Change", "Request / Change"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("Application Problem", "Application Problem"),
                    ("Email/Mailbox Help", "Email/Mailbox Help"),
                    ("Hardware Issue", "Hardware Issue"),
                    ("IT Service Request", "IT Service Request"),
                    ("Printer / Scanner Issue", "Printer / Scanner Issue"),
                    ("Software Installation", "Software Installation"),
                ],
                default="IT Service Request",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Architecture", "Architecture"),
                    ("Corporate", "Corporate"),
                    ("Land", "Land"),
                    ("Transportation", "Transportation"),
                ],
                default="Corporate",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("Akron, OH (W Market St)", "Akron, OH (W Market St)"),
                    ("Albany, NY (Great Oaks Blvd)", "Albany, NY (Great Oaks Blvd)"),
                    (
                        "Baltimore, MD (Research Park Dr)",
                        "Baltimore, MD (Research Park Dr)",
                    ),
                    ("Bluffton, SC (Main St)", "Bluffton, SC (Main St)"),
                    ("Cincinnati, OH (Kenwood Rd)", "Cincinnati, OH (Kenwood Rd)"),
                    (
                        "Clarksville, IN (Quartermaster Ct)",
                        "Clarksville, IN (Quartermaster Ct)",
                    ),
                    ("Columbus, OH (Lyra Dr)", "Columbus, OH (Lyra Dr)"),
                    ("Fairfax, VA (Fair Ridge Dr)", "Fairfax, VA (Fair Ridge Dr)"),
                    (
                        "Fort Myers, FL (International Center)",
                        "Fort Myers, FL (International Center)",
                    ),
                    (
                        "Harrisburg, PA (Highlands Plaza Dr)",
                        "Harrisburg, PA (Highlands Plaza Dr)",
                    ),
                    ("Indianapolis, IN (W 96th St)", "Indianapolis, IN (W 96th St)"),
                    (
                        "Jacksonville, FL (Belfort Pkwy)",
                        "Jacksonville, FL (Belfort Pkwy)",
                    ),
                    (
                        "Jacksonville, FL (Sutton Park Dr)",
                        "Jacksonville, FL (Sutton Park Dr)",
                    ),
                    (
                        "Lake Mary, FL (International Pkwy)",
                        "Lake Mary, FL (International Pkwy)",
                    ),
                    ("Lexington, KY (Corporate Dr)", "Lexington, KY (Corporate Dr)"),
                    ("Louisville, KY (N 7th St)", "Louisville, KY (N 7th St)"),
                    (
                        "Maitland, FL (Maitland Center Pkwy)",
                        "Maitland, FL (Maitland Center Pkwy)",
                    ),
                    ("Morehead, KY (E Main St)", "Morehead, KY (E Main St)"),
                    (
                        "New Albany, IN (Technology Ave)",
                        "New Albany, IN (Technology Ave)",
                    ),
                    ("Orlando, FL (E Pine St)", "Orlando, FL (E Pine St)"),
                    ("Pensacola, FL (W Garden St)", "Pensacola, FL (W Garden St)"),
                    ("Richmond, VA (Arboretum Pkwy)", "Richmond, VA (Arboretum Pkwy)"),
                    ("Tampa, FL (W Cypress St)", "Tampa, FL (W Cypress St)"),
                    ("Weston, FL (N Commerce Pkwy)", "Weston, FL (N Commerce Pkwy)"),
                    (
                        "Wethersfield, CT (Great Meadow Rd)",
                        "Wethersfield, CT (Great Meadow Rd)",
                    ),
                    ("Remote", "Remote"),
                ],
                default="Remote",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="CSATSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 (Poor) to 5 (Excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback comment"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="service_desk.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSAT Survey",
                "verbose_name_plural": "CSAT Surveys",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
