# Generated by Django 5.2.8 on 2026-01-08 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0006_ticket_form_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional technicians watching or helping with this ticket.",
                related_name="collaborating_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
