# Generated by Django 5.2.8 on 2025-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0007_alter_ticket_options_ticket_board_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the first interaction/assignment by a technician.",
                null=True,
            ),
        ),
    ]
