# Generated by Django 5.2.8 on 2025-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0008_ticket_first_response_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the ticket was resolved/closed.",
                null=True,
            ),
        ),
    ]
