# Generated by Django 5.2.8 on 2025-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0009_ticket_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(
                blank=True,
                default="PRIME AE Group, Inc.",
                help_text="Company Name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="manager_name",
            field=models.CharField(
                blank=True,
                default="Marty McFly",
                help_text="Direct Supervisor",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prefer_initials",
            field=models.BooleanField(
                default=False,
                help_text="If checked, displays initials instead of the profile picture.",
            ),
        ),
    ]
