# Generated by Django 5.2.8 on 2025-12-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0010_userprofile_company_userprofile_manager_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("Application Problem", "Application Problem"),
                    ("Email/Mailbox Help", "Email/Mailbox Help"),
                    ("Hardware Issue", "Hardware Issue"),
                    ("IT Service Request", "IT Service Request"),
                    ("Printer / Scanner Issue", "Printer / Scanner Issue"),
                    ("Software Installation", "Software Installation"),
                    ("General Question", "General Question"),
                    ("VP Password Reset", "VP Password Reset"),
                    ("VP Permissions", "VP Permissions"),
                ],
                default="IT Service Request",
                max_length=50,
            ),
        ),
    ]
