# Generated by Django 5.2.8 on 2025-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="announcement_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End time for the announcement (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="announcement_message",
            field=models.TextField(
                default="No known issues at this time.",
                help_text="Message content for the system health announcement",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="announcement_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start time for the announcement (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="announcement_title",
            field=models.CharField(
                default="All Systems Operational",
                help_text="Title of the system health announcement",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="announcement_type",
            field=models.CharField(
                default="info",
                help_text="Type of the announcement (e.g., info, warning, alert, critical)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="vendor_status",
            field=models.JSONField(
                default=list, help_text="List of vendor statuses (stored as JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="support_email",
            field=models.EmailField(
                default="support@primeeng.com",
                help_text="Primary support email address",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="use_mock_data",
            field=models.BooleanField(
                default=False, help_text="Toggle between live data and demo data"
            ),
        ),
    ]
