# Generated by Django 5.2.8 on 2025-11-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Summary / Title of the article', max_length=255)),
                ('category', models.CharField(choices=[('Business & Admin Software', 'Business & Admin Software'), ('Design Applications', 'Design Applications'), ('Hardware & Peripherals', 'Hardware & Peripherals'), ('Internal IT Processes', 'Internal IT Processes'), ('Networking & Connectivity', 'Networking & Connectivity'), ('Printing & Plotting', 'Printing & Plotting'), ('User Accounts & Security', 'User Accounts & Security')], max_length=50)),
                ('subcategory', models.CharField(help_text='e.g., Adobe, Bluebeam, Outlook', max_length=100)),
                ('problem', models.TextField(help_text="The 'Issue' or 'Problem' description.")),
                ('solution', models.TextField(help_text="The 'Resolution' or 'Fix'.")),
                ('internal_notes', models.TextField(blank=True, help_text='IT-only notes (Source, technical details).', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connectwise_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='CW Article ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
