# Generated by Django 5.2.8 on 2025-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='connectwise_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='problem',
            field=models.TextField(verbose_name='Issue / Problem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='solution',
            field=models.TextField(verbose_name='Resolution / Solution'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
