# Generated by Django 5.2.8 on 2025-12-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_alter_article_connectwise_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KBCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "KB Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="knowledge_base.kbcategory",
                verbose_name="Category (New)",
            ),
        ),
        migrations.CreateModel(
            name="KBSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="knowledge_base.kbcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "KB Subcategories",
                "ordering": [
                    "parent__sort_order",
                    "parent__name",
                    "sort_order",
                    "name",
                ],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="subcategory_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="knowledge_base.kbsubcategory",
                verbose_name="Subcategory (New)",
            ),
        ),
    ]
