# Generated by Django 5.2.8 on 2026-01-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareasset",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
