# Generated by Django 5.2.8 on 2026-01-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_hardwareasset_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardwareasset",
            name="last_audit_date",
        ),
        migrations.RemoveField(
            model_name="hardwareasset",
            name="specifications",
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="specs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="support_notes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Support / Warranty Notes"
            ),
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="warranty_expiration",
            field=models.DateField(
                blank=True, null=True, verbose_name="Warranty Expiration"
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="icon",
            field=models.CharField(blank=True, help_text="SVG Icon Key", max_length=50),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="asset_tag",
            field=models.CharField(
                help_text="Unique Asset Tag (e.g., PRIME-1001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.assetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="model_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="notes",
            field=models.TextField(blank=True, verbose_name="General Notes"),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Stock", "In Stock"),
                    ("Deployed", "Deployed"),
                    ("Maintenance", "Maintenance"),
                    ("Retired", "Retired"),
                    ("Lost/Stolen", "Lost/Stolen"),
                ],
                default="In Stock",
                max_length=20,
            ),
        ),
    ]
