# Generated by Django 5.2.8 on 2026-01-03 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_hardwareasset_last_audit_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetcategory",
            name="icon",
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hardwareasset",
            name="vendor",
            field=models.CharField(
                blank=True,
                help_text="Who did we buy this from?",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="asset_tag",
            field=models.CharField(
                help_text="Unique Inventory Tag (e.g. PRIME-LT-04)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.assetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="manufacturer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="model_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="notes",
            field=models.TextField(blank=True, help_text="General remarks", null=True),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="specs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Technical specs (CPU, RAM, IP, etc)",
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="support_notes",
            field=models.TextField(
                blank=True, help_text="Warranty/Support contract details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hardwareasset",
            name="warranty_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
